"""Add Users Table and todo user_id_2

Revision ID: 550587313203
Revises: f9c3fd58f632
Create Date: 2026-04-13 15:51:15.421105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550587313203'
down_revision = 'f9c3fd58f632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_todos_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_todos_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_todos_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_todos_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
